version: '3.1'
services:
  mysql_simdb:
    image: mysql/mysql-server:latest
    container_name: "mysql-poc-simdb"
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'simdb'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"